image: gradle:jdk11

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - gradle build

test:
  stage: test
  script:
    - gradle cucumber
  allow_failure: true  
  artifacts:
    when: always
    paths:
      - target/site/serenity
