image: gradle:jdk11

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - gradle build -x test

test:
  stage: test
  script:
    - gradle clean
    - gradle test
    - gradle report
  artifacts:
    when: always
    paths:
      - target/site/serenity
